<a href="https://colab.research.google.com/github/Nandhini3377/Neural_Network/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np
import matplotlib

print("Python version: {}".format(sys.version))
print("NumPy version: {}".format(np.__version__))
print("Matplotlib version: {}".format(matplotlib.__version__))


Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
NumPy version: 2.0.2
Matplotlib version: 3.10.0


In [ ]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3.0
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

35.7


In [ ]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3.0
output=np.dot(weights,inputs)+bias
print(output)

35.7


In [ ]:
inputs=[1.2,5.1,2.1]
weights=[[0.2,0.8,-0.5],[0.5,-0.91,0.26],[-0.26,-0.27,0.17]]
bias=3.0
output=np.dot(weights,inputs)+bias
print(output)


[ 6.27  -0.495  1.668]


In [ ]:
inputs = [
 [1, 2],
 [3, 4]
]

weights = [
 [2, 3],
 [4, 5]
]
bias=[1,2]
output=np.dot(weights,inputs)+bias
print(output)


[[12 18]
 [20 30]]


In [ ]:
inputs=[[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,0.5],[-0.26,-0.27,0.17,0.5]]

bias=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+bias
print(output)

[[ 4.8    3.71   1.46 ]
 [ 8.9    0.19  -0.54 ]
 [ 1.41   0.251  0.322]]


In [ ]:
inputs=[[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,0.5],[-0.26,-0.27,0.17,0.5]]

bias=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],[-0.5,0.12,-0.33],[-0.44,0.73,-0.13]]
bias2=[-1,2,-0.5]

layer1_outputs=np.dot(inputs,np.array(weights).T)+bias
print(layer1_outputs)
layer2=np.dot(layer1_outputs,np.array(weights2).T)+bias2
print(layer2)

[[ 4.8    3.71   1.46 ]
 [ 8.9    0.19  -0.54 ]
 [ 1.41   0.251  0.322]]
[[-0.3094  -0.4366  -0.0935 ]
 [-0.4066  -2.249   -4.2071 ]
 [-0.73314  1.21886 -0.97903]]


In [ ]:
'''
Associated YT tutorial: https://youtu.be/TEWy9vZcxW4
'''

import numpy as np

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [ ]:
import numpy as np

# XOR Dataset
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Reproducible random numbers
np.random.seed(0)

# Layer 1: 2 inputs -> 2 neurons
weights1 = np.random.randn(2, 2)
bias1 = np.zeros((1, 2))

# Layer 2: 2 neurons -> 1 neuron
weights2 = np.random.randn(2, 1)
bias2 = np.zeros((1, 1))

# Sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Forward Pass

# Hidden layer
hidden_input = np.dot(X, weights1) + bias1
hidden_output = sigmoid(hidden_input)

# Output layer
final_input = np.dot(hidden_output, weights2) + bias2
predictions = sigmoid(final_input)

# Loss
loss = np.mean((y - predictions) ** 2)

print("Hidden Layer Output:")
print(hidden_output)

print("\nPredictions:")
print(predictions)

print("\nLoss:")
print(loss)

Hidden Layer Output:
[[0.5        0.5       ]
 [0.72685773 0.9038621 ]
 [0.85371646 0.59872543]
 [0.93950488 0.93345724]]

Predictions:
[[0.60948312]
 [0.61635951]
 [0.73287215]
 [0.69895629]]

Loss:
0.2696367200181884


In [12]:
import numpy as np

# XOR Dataset
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

# initialise random numbers
np.random.seed(0)

n_input = 2
n_hidden = 4
n_output = 1

# Layer 1: n_input -> n_hidden
weights1 = np.random.randn(n_input, n_hidden)
bias1 = np.zeros((1, n_hidden))

# Layer 2: n_hidden -> n_output
weights2 = np.random.randn(n_hidden, n_output)
bias2 = np.zeros((1, n_output))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

learning_rate = 0.5
epochs = 10000

for epoch in range(epochs):
    #  Forward pass
    hidden_input = np.dot(X, weights1) + bias1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights2) + bias2
    predictions = sigmoid(final_input)

    loss = np.mean((y - predictions) ** 2)

    # Backward pass
    error_output = (predictions - y)
    delta_output = error_output * sigmoid_derivative(predictions)

    error_hidden = np.dot(delta_output, weights2.T)
    delta_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Gradients
    grad_weights2 = np.dot(hidden_output.T, delta_output)
    grad_bias2 = np.sum(delta_output, axis=0, keepdims=True)

    grad_weights1 = np.dot(X.T, delta_hidden)
    grad_bias1 = np.sum(delta_hidden, axis=0, keepdims=True)

    # Update weights
    weights2 -= learning_rate * grad_weights2
    bias2 -= learning_rate * grad_bias2
    weights1 -= learning_rate * grad_weights1
    bias1 -= learning_rate * grad_bias1

    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d} | Loss: {loss:.6f}")

print("\nFinal predictions:")
print(predictions)
print("\nFinal loss:", loss)
print("\nRounded predictions (threshold 0.5):")
print(np.round(predictions))

Epoch     0 | Loss: 0.326682
Epoch  1000 | Loss: 0.007722
Epoch  2000 | Loss: 0.001993
Epoch  3000 | Loss: 0.001091
Epoch  4000 | Loss: 0.000740
Epoch  5000 | Loss: 0.000557
Epoch  6000 | Loss: 0.000445
Epoch  7000 | Loss: 0.000369
Epoch  8000 | Loss: 0.000315
Epoch  9000 | Loss: 0.000275

Final predictions:
[[0.01595352]
 [0.98459352]
 [0.9858926 ]
 [0.0168199 ]]

Final loss: 0.00024345055123399203

Rounded predictions (threshold 0.5):
[[0.]
 [1.]
 [1.]
 [0.]]
