<a href="https://colab.research.google.com/github/Nandhini3377/Neural_Network/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np
import matplotlib

print("Python version: {}".format(sys.version))
print("NumPy version: {}".format(np.__version__))
print("Matplotlib version: {}".format(matplotlib.__version__))


Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
NumPy version: 2.0.2
Matplotlib version: 3.10.0


In [2]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3.0
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

35.7


In [3]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3.0
output=np.dot(weights,inputs)+bias
print(output)

35.7


In [4]:
inputs=[1.2,5.1,2.1]
weights=[[0.2,0.8,-0.5],[0.5,-0.91,0.26],[-0.26,-0.27,0.17]]
bias=3.0
output=np.dot(weights,inputs)+bias
print(output)


[ 6.27  -0.495  1.668]


In [8]:
inputs = [
 [1, 2],
 [3, 4]
]

weights = [
 [2, 3],
 [4, 5]
]
bias=[1,2]
output=np.dot(weights,inputs)+bias
print(output)


[[12 18]
 [20 30]]


In [13]:
inputs=[[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,0.5],[-0.26,-0.27,0.17,0.5]]

bias=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+bias
print(output)

[[ 4.8    3.71   1.46 ]
 [ 8.9    0.19  -0.54 ]
 [ 1.41   0.251  0.322]]


In [15]:
inputs=[[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,0.5],[-0.26,-0.27,0.17,0.5]]

bias=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],[-0.5,0.12,-0.33],[-0.44,0.73,-0.13]]
bias2=[-1,2,-0.5]

layer1_outputs=np.dot(inputs,np.array(weights).T)+bias
print(layer1_outputs)
layer2=np.dot(layer1_outputs,np.array(weights2).T)+bias2
print(layer2)

[[ 4.8    3.71   1.46 ]
 [ 8.9    0.19  -0.54 ]
 [ 1.41   0.251  0.322]]
[[-0.3094  -0.4366  -0.0935 ]
 [-0.4066  -2.249   -4.2071 ]
 [-0.73314  1.21886 -0.97903]]


In [16]:
'''
Associated YT tutorial: https://youtu.be/TEWy9vZcxW4
'''

import numpy as np

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
